pref("extensions.zotero-mineru.apiBaseURL", "https://mineru.net/api/v4");
pref("extensions.zotero-mineru.apiToken", "");
pref("extensions.zotero-mineru.modelVersion", "pipeline");
pref("extensions.zotero-mineru.noteIncludeImages", false);
pref("extensions.zotero-mineru.pollIntervalSec", 3);
pref("extensions.zotero-mineru.timeoutSec", 120);
pref("extensions.zotero-mineru.noteTitlePrefix", "MinerU Parse");
pref("extensions.zotero-mineru.llmApiBaseURL", "");
pref("extensions.zotero-mineru.llmApiKey", "");
pref("extensions.zotero-mineru.llmModel", "");
pref("extensions.zotero-mineru.summaryLanguage", "English");
pref("extensions.zotero-mineru.summaryRequestJSON", "");
pref("extensions.zotero-mineru.translateLanguage", "English");
pref("extensions.zotero-mineru.translateChunkSize", 20000);
pref("extensions.zotero-mineru.translateConcurrency", 3);
pref("extensions.zotero-mineru.translateRetryCount", 2);
pref("extensions.zotero-mineru.translateRequestJSON", "");
